config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#home"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks"}
  resources :users do 
      resources :brands do 
        resources :call_to_actions, except: [:new, :create]
      end 
      resources :clips
  		resources :call_to_actions, only: [:new, :create]
	end 

  get "/:short_link" => "clips#short", as: :short_link_path
  post "/translate" => "clips#translate"
  post "/counter" => "call_to_actions#counter"
  post "/user/:user_id/clip/:id/archive" => "clips#archive", as: :archive_clip
  post "/user/:user_id/call_to_action/:id/archive" => "call_to_actions#archive", as: :archive_cta
  get "/user/:user_id/archived" => "users#archived", as: :user_archived_list
end

app/controllers/call_to_actions_controller.rb
class CallToActionsController < ApplicationController
  before_action :set_call_to_action, only: [:show, :edit, :update, :destroy]

  # GET /call_to_actions
  # GET /call_to_actions.json
  def index
    @call_to_actions = CallToAction.all
  end

  # GET /call_to_actions/1
  # GET /call_to_actions/1.json
  def show
  end

  # GET /call_to_actions/new
  def new
    @call_to_action = CallToAction.new
  end

  # GET /call_to_actions/1/edit
  def edit
  end

  def counter       
    @cta = CtaCount.new
    raw = params[:cta_count].split
    short_link = raw[0].split("")
    short_link = short_link[1, short_link.count].join
    cta_id = raw[1]
    @cta.clip_id = Clip.find_by(short_link: short_link).id
    @cta.call_to_action_id = cta_id.to_i
    if @cta.save
      render json: {response: "Successfully created new count"}
    else 
      render json: {response: @cta.errors}
    end
  end 

  def archive 
    @cta = CallToAction.find(params[:id])
    @cta.archived!
    @cta_clips = @cta.clips
    @cta_clips.each {|x| x.archived!}
    redirect_to request.referrer
  end 

  # POST /call_to_actions
  # POST /call_to_actions.json
  def create
    @call_to_action = CallToAction.new(call_to_action_params)

    respond_to do |format|
      if @call_to_action.save
        format.html { redirect_to current_user, notice: 'Call to action was successfully created.' }
        format.json { render :show, status: :created, location: @call_to_action }
      else
        format.html { render :new }
        format.json { render json: @call_to_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /call_to_actions/1
  # PATCH/PUT /call_to_actions/1.json
  def update
    respond_to do |format|
      if @call_to_action.update(call_to_action_params)
        format.html { redirect_to user_path(current_user), notice: 'Call to action was successfully updated.' }
        format.json { render :show, status: :ok, location: @call_to_action }
      else
        format.html { render :edit }
        format.json { render json: @call_to_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /call_to_actions/1
  # DELETE /call_to_actions/1.json
  def destroy
    @call_to_action.destroy
    respond_to do |format|
      format.html { redirect_to call_to_actions_url, notice: 'Call to action was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_call_to_action
      @call_to_action = CallToAction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def call_to_action_params
      params.permit(:description, :button_text, :button_link, :position, :bg_color, :bg_border_size, :bg_border_type, :bg_border_color, :bg_border_radius, :btn_color, :btn_border_size, :btn_border_type, :btn_border_color, :btn_border_radius, :user_id, :brand_id)
    end
end

app/helpers/call_to_actions_helper.rb
module CallToActionsHelper
end

app/views/call_to_actions/_form.html.erb
<%= form_with(url: user_call_to_actions_path, local: true) do |form| %>
  <% if call_to_action.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(call_to_action.errors.count, "error") %> prohibited this call_to_action from being saved:</h2>

      <ul>
      <% call_to_action.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <!-- general customization of CTA -->
  <% @brand_list = Brand.where(user_id: current_user.id) %> 
  <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
    
    <%= form.label :select_brand %>
    <%= form.select :brand_id, @brand_list.collect {|brand| [brand.name, brand.id] },{include_blank: true},id:"brand-input"%> 

    <%= form.label :description %>
    <%= form.text_field :description, maxlength:85, class:"form-control", id:"desc-input", onkeyup:"descLive()", placeholder:"Create your Call To Action Today! (Psst... max 85 characters only)" %>

    <%= form.label :button_text %>
    <%= form.text_field :button_text, maxlength:12, class:"form-control", id:"btn-text-input", onkeyup:"btnTextLive()", placeholder:"check it out" %> 

    <%= form.label :button_link %>
    <%= form.url_field :button_link,class:"form-control", id:"button-link-input", onchange:"buttonLinkLive()", placeholder:"https://www.sample.com" %>

    <%= form.label :position %>
    <%= form.select :position, [["left","flex-start"],["middle","center"],["right","flex-end"]], {class:"form-control"}, {id:"position-input", onchange:"positionLive()"} %>
  </div>

  <%= form.label :border_radius%>
  <div style="display:flex;">
    <span id="bg-border-radius-output">0</span>
    <%= form.range_field :bg_border_radius, in: 0..50, step:0.1,id:"bg-border-radius-input", onchange:"bgRadiusLive()" %>
    
  </div>
  <!-- Customization of CTA elements  -->
  
  <div class="form-group">
    <p><strong>Background</strong></p>
    
    <%= form.label :color %>
    <div style="display:flex;"">
      <%= form.color_field :bg_color, class:"form-control color-tab", value:"#ADD8E6", id:"bg-color-input", onchange:"bgColorLive()"%>
      <span id="bg-color-output">#ADD8E6</span>      
    </div>

    <%= form.label :outline_type %>
    <%= form.select :bg_outline_type, ["none","solid","dotted","dashed","double","groove","ridge","inset","outset"], {include_blank:false},{class:"form-control", id:"bg-outline-type-input", onchange:"bgoutlineTypeLive()"} %>

    <%= form.label :outline_size %>
    <%= form.number_field :bg_outline_size, in: 0..20, class:"form-control", id:"bg-outline-size-input", onchange:"bgoutlineSizeLive()" %>
    
    <%= form.label :outline_color %>
    <div style="display:flex;">
      <%= form.color_field :bg_outline_color, class:"form-control color-tab", value:"#000000", id:"bg-outline-color-input", onchange:"bgoutlineColorLive()" %>
      <span id="bg-outline-color-output">#000000</span>
    </div>
    
  </div>

  <!-- Cutomization of CTA buttons elements  -->
  <div class="form-group">
    <p><strong>Button</strong></p>
    
    <%= form.label :color %>
    <div style="display:flex;">
      <%= form.color_field :btn_color, class:"form-control color-tab", value:"#ff9300", id:"btn-color-input", onchange:"btnColorLive()" %>
      <span id="btn-color-output">#ff9300</span>
    </div>
    
    <%= form.label :border_radius %>
    <div style="display:flex;">
      <span id="btn-border-radius-output">0</span>
      <%= form.range_field :btn_border_radius, in: 0..50, step:0.1,id:"btn-border-radius-input", onchange:"btnRadiusLive()" %>
    </div>

    <%= form.label :outline_type %>
    <%= form.select :btn_outline_type, ["none","solid","dotted","dashed","double","groove","ridge","inset","outset"], {include_blank:false},{class:"form-control", id:"btn-outline-type-input", onchange:"btnoutlineTypeLive()"} %>

    <%= form.label :outline_size %>
    <%= form.number_field :btn_outline_size, in: 0..20, class:"form-control", id:"btn-outline-size-input", onchange:"btnoutlineSizeLive()" %>
    
    

    <%= form.label :outline_color %>
    <div style="display:flex;">
      <%= form.color_field :btn_outline_color, class:"form-control color-tab", value:"#000000", id:"btn-outline-color-input", onchange:"btnoutlineColorLive()" %>
      <span id="btn-outline-color-output">#000000</span>
    </div>

  </div>


  <div class="actions">
    <%= form.submit "Create", class:"btn btn-lg btn-warning" %>
  </div>
<% end %>

app/views/call_to_actions/edit.html.erb
<h1>Editing Call To Action</h1>

<%= render 'form', call_to_action: @call_to_action %>

<%= link_to 'Show', @call_to_action %> |
<%= link_to 'Back', call_to_actions_path %>

app/views/call_to_actions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Call To Actions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @call_to_actions.each do |call_to_action| %>
      <tr>
        <td><%= link_to 'Show', call_to_action %></td>
        <td><%= link_to 'Edit', edit_call_to_action_path(call_to_action) %></td>
        <td><%= link_to 'Destroy', call_to_action, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Call To Action', new_call_to_action_path %>

app/views/call_to_actions/new.html.erb
<div class="cta-new-main">

	<div class="cta-new-left-panel">
		<h1>New Call To Action</h1>
		<%= link_to 'Back', user_path(current_user) %>
		<%= render 'form', call_to_action: @call_to_action %>
	</div>
	
	<div class="cta-new-right-panel">
		<div class="iframe-cover"></div>
		<iframe src="/" frameborder="0" width="100%" height="100%"></iframe>
	
	<!-- Live display of CTA -->
		<div id="cta-container">
			<div class="cta-new-live" id="cta-new-live">
				<div class="cta-new-live-logo">
					<%= image_tag("clipit-logo.png", width:"50px", height:"50px", id:"brand-output") %>
				</div>
				<div class="cta-new-live-middlebox">
					<div class="cta-new-live-name">
						<p id="cta-new-live-name">Clip It Today!</p>
					</div>
					<div class="cta-new-live-description">
						<h6><strong id="desc-output">
							Create your Call To Action Today! (Psst... max 85 characters only)
						</strong></h6>
					</div>
					<div class="cta-new-live-close-mobile">
						<p>X</p>
					</div>
				</div>
				<div class="cta-new-live-endbox">
					<div class="cta-new-live-close">
						<p>X</p>
					</div>
					<div class="cta-new-live-name-mobile">
						<div class="cta-new-live-logo-mobile">
							<%= image_tag("clipit-logo.png", width:"50px", height:"50px", id:"brand-output-mobile") %>
						</div>
						<p id="cta-new-live-name-mobile">Clip It Today!</p>
					</div>
					<div class="cta-new-live-button">
						<a href="#" target="_blank" id="button-link-live">
							<button class="btn" id="btn-text-output">check it out</button>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	

</div>

app/views/call_to_actions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_call_to_action_path(@call_to_action) %> |
<%= link_to 'Back', call_to_actions_path %>