config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#home"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks"}
  resources :users do 
      resources :brands do 
        resources :call_to_actions, except: [:new, :create]
      end 
      resources :clips
  		resources :call_to_actions, only: [:new, :create]
	end 

  get "/:short_link" => "clips#short", as: :short_link_path
  post "/translate" => "clips#translate"
  post "/counter" => "call_to_actions#counter"
  post "/user/:user_id/clip/:id/archive" => "clips#archive", as: :archive_clip
  post "/user/:user_id/call_to_action/:id/archive" => "call_to_actions#archive", as: :archive_cta
  get "/user/:user_id/archived" => "users#archived", as: :user_archived_list
end

app/models/clip.rb
class Clip < ApplicationRecord
	belongs_to :call_to_action
	belongs_to :user
	has_many :cta_counts
	UNIQUE_ID_LENGTH = 7
	validates :page_link, presence: true, on: :create 
	before_create :generate_short_url 
	enum status: {active: 0, archived: 1}

	def generate_short_url 
		url = ([*('a'..'z'),*('A'..'Z'),*('0'..'9')].sample(UNIQUE_ID_LENGTH)).join
		old_url = Clip.find_by(short_link: url)
		if old_url.present? 
			self.generate_short_url
		else 
			self.short_link = url 
		end 
	end 

	def self.total_count(user)
		all = self.where(user_id: user.id)
		count = 0 
		all.each do |x| 
			count += x.count 
		end 
		return count
	end
end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController
  before_action :set_clip, only: [:show, :edit, :update, :destroy]

  # GET /clips
  # GET /clips.json
  def index
    @clips = Clip.all
  end

  # @client_display if true prevents the loading of patial navbar
  def short
    @clip = Clip.find_by(short_link: params[:short_link])
    @clip.update(count: @clip.count + 1)
    @client_display = true
  end 

  def archive 
    @clip = Clip.find(params[:id])
    @clip.archived!
    redirect_to request.referrer
  end 

  # GET /clips/1
  # GET /clips/1.json
  def show
    @client_display = true
  end


  # GET /clips/new
  def new
    @clip = Clip.new
  end

  # GET /clips/1/edit
  def edit
  end

  # GET /translate
  def translate 

    @brand_logo = Brand.find(params[:brand_id])
    @brand_name = Brand.find(params[:brand_id]).name
    if @brand_logo.logo.file.nil? 
      @brand = {url:"http://localhost:3000/assets/clipit-logo-19f64c3a05955cb803c20e688b74f2419f1ed60fdfc5d3d928efd26cb65188e3.png", name: @brand_name}
    else 
      @brand = {url: @brand_logo.logo.url, name: @brand_name }
    end 
    render json: @brand

  end 

  # POST /clips
  # POST /clips.json
  def create
    @clip = Clip.new(clip_params)
    respond_to do |format|
      if @clip.save
        format.html { redirect_to current_user, notice: 'Clip was successfully created.' }
        format.json { render :show, status: :created, location: @clip }
      else
        @clip.errors
        format.html { redirect_to current_user}
        format.json { render json: @clip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clips/1
  # PATCH/PUT /clips/1.json
  def update
    respond_to do |format|
      if @clip.update(clip_params)
        format.html { redirect_to current_user, notice: 'Clip was successfully updated.' }
        format.json { render :show, status: :ok, location: @clip }
      else
        format.html { render :edit }
        format.json { render json: @clip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clips/1
  # DELETE /clips/1.json
  def destroy
    @clip.destroy
    respond_to do |format|
      format.html { redirect_to clips_url, notice: 'Clip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clip
      @clip = Clip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clip_params
      params.permit(:page_link, :call_to_action_id, :user_id)
    end
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/views/clips/_form.html.erb
<%= form_with(model: clip, local: true) do |form| %>
  <% if clip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(clip.errors.count, "error") %> prohibited this clip from being saved:</h2>

      <ul>
      <% clip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clips/edit.html.erb
<h1>Editing Clip</h1>

<%= render 'form', clip: @clip %>

<%= link_to 'Show', @clip %> |
<%= link_to 'Back', clips_path %>

app/views/clips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clips</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clips.each do |clip| %>
      <tr>
        <td><%= link_to 'Show', clip %></td>
        <td><%= link_to 'Edit', edit_clip_path(clip) %></td>
        <td><%= link_to 'Destroy', clip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clip', new_clip_path %>

app/views/clips/new.html.erb
<h1>New Clip</h1>

<%= render 'form', clip: @clip %>

<%= link_to 'Back', clips_path %>

app/views/clips/short.html.erb
<iframe class="iframe-page" src="<%=@clip.page_link%>" width="100%" height="900px" frameborder="0"></iframe>

<!-- Live display of CTA -->
<div id="cta-container" style="justify-content: <%= @clip.call_to_action.position %>; width: 100%;">
	<div class="cta-new-live" style="background-color: <%= @clip.call_to_action.bg_color %>; border-radius: <%= @clip.call_to_action.bg_border_radius  + "px" %>; border-style: <%= @clip.call_to_action.bg_border_type %> ; border-width:<%= @clip.call_to_action.bg_border_size %> ; border-color: <%= @clip.call_to_action.bg_border_color %>;" >
		<div class="cta-new-live-logo">
			<% if @clip.call_to_action.brand.logo.file.nil? %> 
				<%= image_tag("clipit-logo.png", width:"50px", height:"50px", id:"brand-output") %>
			<% else %>
				<%= image_tag(@clip.call_to_action.brand.logo) %> 
			<% end %>
		</div>
		<div class="cta-new-live-middlebox">
			<div class="cta-new-live-name">
				<p><%= @clip.call_to_action.brand.name %></p>
			</div>
			<div class="cta-new-live-description">
				<h6><strong>
					<%= @clip.call_to_action.description %>
				</strong></h6>
			</div>
			<div class="cta-new-live-close-mobile">
				<a href="<%=@clip.page_link%>">
					<p>X</p>
				</a>
			</div>
		</div>
		<div class="cta-new-live-endbox">
			<div class="cta-new-live-close">
				<a href="<%=@clip.page_link%>">
					<p>X</p>
				</a>
			</div>
			<div class="cta-new-live-name-mobile">
				<div class="cta-new-live-logo-mobile">
					<% if @clip.call_to_action.brand.logo.file.nil? %> 
						<%= image_tag("clipit-logo.png", width:"50px", height:"50px", id:"brand-output") %>
					<% else %>
						<%= image_tag(@clip.call_to_action.brand.logo) %> 
					<% end %>
				</div>
				<p id="cta-new-live-name-mobile">Clip It Today!</p>
			</div>
			<div class="cta-new-live-button">
				<a href=<%= @clip.call_to_action.button_link %> target="_blank" >
					<button class="btn" id="short-link-page-button" value=<%= @clip.call_to_action.id %> style="background-color: <%= @clip.call_to_action.btn_color %>; border-radius: <%= @clip.call_to_action.btn_border_radius  + "px" %>; border-style: <%= @clip.call_to_action.btn_border_type %> ; border-width:<%= @clip.call_to_action.btn_border_size %> ; border-color: <%= @clip.call_to_action.btn_border_color %>;"><%=@clip.call_to_action.button_text%></button>
				</a>
			</div>
		</div>
	</div>
</div>

app/views/clips/show.html.erb
<iframe class="iframe-page" src="<%=@clip.page_link%>" width="100%" height="100%" frameborder="0"></iframe>

<!-- Live display of CTA -->
<div id="cta-container" style="justify-content: <%= @clip.call_to_action.position %>; width: 100%;">
	<div class="cta-new-live" style="background-color: <%= @clip.call_to_action.bg_color %>; border-radius: <%= @clip.call_to_action.bg_border_radius  + "px" %>; border-style: <%= @clip.call_to_action.bg_border_type %> ; border-width:<%= @clip.call_to_action.bg_border_size %> ; border-color: <%= @clip.call_to_action.bg_border_color %>;" >
		<div class="cta-new-live-logo">
			<% if @clip.call_to_action.brand.logo.file.nil? %> 
				<%= image_tag("clipit-logo.png", width:"50px", height:"50px", id:"brand-output") %>
			<% else %>
				<%= image_tag(@clip.call_to_action.brand.logo) %> 
			<% end %>
		</div>
		<div class="cta-new-live-middlebox">
			<div class="cta-new-live-name">
				<p><%= @clip.call_to_action.brand.name %></p>
			</div>
			<div class="cta-new-live-description">
				<h6><strong>
					<%= @clip.call_to_action.description %>
				</strong></h6>
			</div>
			<div class="cta-new-live-close-mobile">
				<a href="<%=@clip.page_link%>">
					<p>X</p>
				</a>
			</div>
		</div>
		<div class="cta-new-live-endbox">
			<div class="cta-new-live-close">
				<a href="<%=@clip.page_link%>">
					<p>X</p>
				</a>
			</div>
			<div class="cta-new-live-name-mobile">
				<div class="cta-new-live-logo-mobile">
					<% if @clip.call_to_action.brand.logo.file.nil? %> 
						<%= image_tag("clipit-logo.png", width:"50px", height:"50px", id:"brand-output") %>
					<% else %>
						<%= image_tag(@clip.call_to_action.brand.logo) %> 
					<% end %>
				</div>
				<p id="cta-new-live-name-mobile">Clip It Today!</p>
				</div>
			<div class="cta-new-live-button">
				<a href=<%= @clip.call_to_action.button_link%> target="_blank" >
					<button class="btn" style="background-color: <%= @clip.call_to_action.btn_color %>; border-radius: <%= @clip.call_to_action.btn_border_radius  + "px" %>; border-style: <%= @clip.call_to_action.btn_border_type %> ; border-width:<%= @clip.call_to_action.btn_border_size %> ; border-color: <%= @clip.call_to_action.btn_border_color %>;"><%=@clip.call_to_action.button_text%>
					</button>
				</a>
			</div>
		</div>
	</div>
</div>
		