config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#home"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks"}
  resources :users do 
      resources :brands do 
        resources :call_to_actions, except: [:new, :create]
      end 
      resources :clips
  		resources :call_to_actions, only: [:new, :create]
	end 

  get "/:short_link" => "clips#short", as: :short_link_path
  post "/translate" => "clips#translate"
  post "/counter" => "call_to_actions#counter"
  post "/user/:user_id/clip/:id/archive" => "clips#archive", as: :archive_clip
  post "/user/:user_id/call_to_action/:id/archive" => "call_to_actions#archive", as: :archive_cta
  get "/user/:user_id/archived" => "users#archived", as: :user_archived_list
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
	has_and_belongs_to_many :oauth_credentials
	has_many :brands
	has_many :call_to_actions
	has_many :clips

	def self.from_omniauth(access_token)
	  data = access_token.info
	  user = User.where(:email => data["email"]).first

	  unless user
	    password = Devise.friendly_token[0,20]
	    user = User.create(email: data["email"],
	      password: password, password_confirmation: password
	    )
	  end
	  user
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end


end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def after_sign_up_path_for(resource)
    user_path(curret_user)
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@clip = Clip.new
		@user = User.find(params[:id])
		if @user != current_user
			redirect_to '/'
		end	
		@brand_list = @user.brands 
		@cta_list = @user.call_to_actions.where(status: 0)
		@clip_list = @user.clips.where(status: 0)
	end 

	def archived 
		@user = User.find(params[:user_id])
		if @user != current_user
			redirect_to '/'
		end	
		@brand_list = @user.brands 
		@cta_list = @user.call_to_actions.where(status: 1)
		@clip_list = @user.clips.where(status: 1)
	end  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/archived.html.erb
<section class="dashboard-main">

<!-- Dashboard left panel -->

	<div class="dashboard-sub-left">
		<div class="dashboard-title">
			<a href="<%=user_path(current_user)%>"><h2><i class="fas fa-tachometer-alt"></i>&nbspDashboard</h2></a>
		</div>
		<div class="dashboard-sub-left-menu-container">
			<h3><i class="fas fa-edit"></i>&nbspManage</h3>
			<div class="dashboard-sub-left-menu">
				<div>
					<a href=<%= user_brands_path(current_user)%>>
						<h4><i class="fas fa-caret-right"></i>&nbspBrand</h4>
					</a>
					
				</div>
				<div>
					<a href="<%= user_archived_list_path(current_user)%>">
						<h4><i class="fas fa-caret-right"></i>&nbspArchives</h4>
					</a>
				</div>
			</div>
		</div>
		<div class="dashboard-sub-left-menu-container">
			<h3><i class="fas fa-user-circle"></i>&nbspAccount</h3>
			<div class="dashboard-sub-left-menu">
				<div>
					<a href=<%=edit_user_registration_path %>>
						<h4><i class="fas fa-caret-right"></i>&nbspManage Password</h4>
					</a>
				</div>
				<div>
					<a href="#">
						<h4><i class="fas fa-caret-right"></i>&nbspSubscription</h4>
					</a>
				</div>
			</div>

		</div>
		<div class="dashboard-sub-left-menu-container dashboard-question">
			<a href="#">
				<h3><i class="fas fa-question-circle"></i>&nbspSupport</h3>
			</a>
		</div>
	</div>


<!-- Dash bord right panel -->

	<div class="dashboard-sub-right">
		<!-- Listing of all the CTA owned by this user  -->
		<section class="cta-section">
			
			<!-- title and create button -->
			<div class="dashboard-cta-title">
				<div id="dashboard-cta-title-text">
					<h3>Archived Call To Actions</h3>
				</div>
			</div>

			<!-- headings of the list  -->

			<div class="dashboard-cta-headers row">
				<div class="col-lg-1 col-md-1 col-sm-1">
				</div>	
				<div class="col-lg-2 col-md-2 col-sm-2">
					<p>Brand</p>
				</div>
				<div class="col-lg-5 col-md-5 col-sm-5">
					<p>CTA Message</p>
				</div>	
				<div class="col-lg-1 col-md-1 col-sm-1">
					<p>Clips</p>
				</div>	
				<div class="col-lg-1 col-md-1 col-sm-1">
					<p>Clicks</p>
				</div>	
				<div class="col-lg-2 col-md-2 col-sm-2">
				</div>	
			</div>
			<!-- Listing of all call to actions created -->
			<% if @cta_list.present? %>
				<% @count = 0 %>
				<% @count_mobile = 0 %>
				<% @cta_list.each do |x| %> 
					<div class="dashboard-cta-list row">
						<div class="col-lg-1 col-md-1 col-sm-1" id="dashboard-cta-list-num">
							<p><%= @count += 1 %></p>
						</div>	
						<div class="col-lg-2 col-md-2 col-sm-2">
							<p><%= x.brand.name %></p>
						</div>
						<div class="col-lg-5 col-md-5 col-sm-5">
							<p><%= x.description.truncate(40) %></p>
						</div>	
						<div class="col-lg-1 col-md-1 col-sm-1">
							<p><%= x.clips.count %></p>
						</div>	
						<div class="col-lg-1 col-md-1 col-sm-1">
							<p><%= x.cta_counts.count %></p>
						</div>	
					</div>

				<!-- end of desktop version --> 

					<!-- mobile version --> 
					<div class="dashboard-cta-list-mobile">
						<div id="dashboard-cta-list-num">
							<p><%= @count_mobile += 1 %></p>
						</div>	
						<div>
							<p>Brand: <%= x.brand.name %></p>
						</div>
						<div>
							<p>Message: <%= x.description.truncate(30) %></p>
						</div>	
						<div>
							<p>Clips: <%= x.clips.count %></p>
						</div>	
						<div>
							<p>Clicks: <%= x.cta_counts.count %></p>
						</div>	
					</div>

					<!-- end of mobile version -->
				<% end %>
			<% else %>
				<h6 class="no-item-message">Nope, you have not archived any CTA so far.</h6>
			<% end %>
		</section>

		<!-- end of CTA list -->


		<!-- Listing of all the Clips owned by this user  -->
		<section class="clip-section">
			
			<!-- title and create button -->
			<div class="dashboard-clip-title">
				<div  class="col-lg-3" id="dashboard-clip-title-text">
					<h3>Archived Clips</h3>
				</div>
				
				<div class="col-lg-9" id="dashboard-clip-title-form">
				</div>
			</div>

			<!-- headings of the Clip list  -->

			<div class="dashboard-cta-headers row">
				<div class="col-lg-1 col-md-1 col-sm-1">
				</div>	
				<div class="col-lg-4 col-md-4 col-sm-4">
					<p>CTA Message</p>
				</div>	
				<div class="col-lg-3 col-md-3 col-sm-3">
					<p>Page Link</p>
				</div>	
				<div class="col-lg-1 col-md-1 col-sm-1">
					<p>Visits</p>
				</div>	
				<div class="col-lg-1 col-md-1 col-sm-1">
					<p>Clicks</p>
				</div>	
				<div class="col-lg-1 col-md-1 col-sm-1">
					<p>Conversion</p>
				</div>	
				<div class="col-lg-1 col-md-1 col-sm-1">
				</div>	
			</div>
			<!-- Listing of all Clips created -->
			<% @count = 0 %>
			<% @count_mobile = 0 %>
			<% if @clip_list.present? %>
				<% @clip_list.each do |x| %>
				<div class="dashboard-clip-list-desktop">
					<div class="dashboard-clip-list row">
						<div class="col-lg-1 col-md-1 col-sm-1" id="dashboard-clip-list-num">
							<p><%= @count += 1 %></p>
						</div>		
						<div class="col-lg-4 col-md-4 col-sm-4 archived-cta-message-container">
							<p class="archived-cta-message">
								<%= x.call_to_action.description.truncate(30) %>
							</p>
							<p class="pop-up-cta-message">
								<%= x.call_to_action.description %>
							</p>							
						</div>
						<div class="col-lg-3 col-md-3 col-sm-3 archived-page-link-container">
							<p class="archived-page-link">
								<%= x.page_link.truncate(25) %>
							</p>
							<p class="pop-up-page-link">
								<%= x.page_link %>
							</p>	
						</div>
						<div class="col-lg-1 col-md-1 col-sm-1">
							<p><%= x.count %></p>
						</div>	
						<div class="col-lg-1 col-md-1 col-sm-1">
							<p><%= x.cta_counts.where(call_to_action_id: x.call_to_action.id).count %></p></p>
						</div>	
						<div class="col-lg-1 col-md-1 col-sm-1">
							<p>
							<% if x.call_to_action != 0 && x.count != 0%>
								<%= ((x.cta_counts.where(call_to_action_id: x.call_to_action.id).count.to_f / x.count.to_f)*100).round(2).to_s + "%" %>
							<% else %>
								<%= "N/A" %>
							<% end %> 
							</p>
						</div>	
						<div class="col-lg-1 col-md-1 col-sm-1" id="dashboard-clip-list-buttons">
							<%= link_to "View Page",user_clip_path(user_id: current_user.id, id: x.id),target:"_blank" %>
						</div>	
					</div>
					<div id="hover-display" class="dashboard-clip-list row">
						<div id="clip-sub-list-first" class="col-lg-1 col-md-1 col-sm-1">
						</div>
						<div id="clip-sub-list-second-a" class="col-lg-2">
							<p>
								Call To Action
							</p>
						</div>
						<div id="clip-sub-list-second-b" class="col-lg-9">
							<p>
								<%= x.call_to_action.description %>
							</p>
						</div>
					</div>
					<div id="hover-display" class="dashboard-clip-list row">
						<div id="clip-sub-list-first" class="col-lg-1">
						</div>
						<div id="clip-sub-list-second-a" class="col-lg-2">
							<p>
								Link to Page
							</p>
						</div>
						<div id="clip-sub-list-second-b" class="col-lg-9">
							<p>
								<%= x.page_link %>
							</p>
						</div>
					</div>
					</div>
				<!-- Mobile Version -->

					<div class="dashboard-clip-list-mobile">
						<div class="dashboard-clip-list-mobile-mobile">
							<div class="col-lg-1" id="dashboard-clip-list-num">
								<p><%= @count_mobile += 1 %></p>
							</div>		
							<div>
								<p>
									<%= x.call_to_action.description %>
								</p>
							</div>
							<div>
								<p>
									<%= x.page_link %>
								</p>
							</div>
							<div>
								<p>Visits: <%= x.count %></p>
							</div>	
							<div>
								<p>Clicks: <%= x.cta_counts.where(call_to_action_id: x.call_to_action.id).count %></p>
							</div>	
							<div>
								<p>Conversion:
								<% if x.call_to_action != 0 && x.count != 0%>
									<%=((x.cta_counts.where(call_to_action_id: x.call_to_action.id).count.to_f / x.count.to_f)*100).round(2).to_s + "%" %>
								<% else %>
									<%= "N/A" %>
								<% end %> 
								</p>
							</div>	
					</div>
				
				<!-- end of mobile version -->

				<% end %>
			<% else %>
				<h6 class="no-item-message">Hmmm... seems like you have not arhived any clips yet.</h6>

			<% end %>
		</section>

		<!-- end of Clip list -->

	</div>
</section>