config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#home"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks"}
  resources :users do 
      resources :brands do 
        resources :call_to_actions, except: [:new, :create]
      end 
      resources :clips
  		resources :call_to_actions, only: [:new, :create]
	end 

  get "/:short_link" => "clips#short", as: :short_link_path
  post "/translate" => "clips#translate"
  post "/counter" => "call_to_actions#counter"
  post "/user/:user_id/clip/:id/archive" => "clips#archive", as: :archive_clip
  post "/user/:user_id/call_to_action/:id/archive" => "call_to_actions#archive", as: :archive_cta
  get "/user/:user_id/archived" => "users#archived", as: :user_archived_list
end

app/models/brand.rb
class Brand < ApplicationRecord
	belongs_to :user
	has_many :call_to_actions, dependent: :destroy
	mount_uploader :logo, LogoUploader
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brand = Brand.new
    @brands = Brand.all
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
    @brand = Brand.find(params[:id])
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        if @brand.errors.present? 
          @brand.errrors
        end 
        format.html { redirect_to user_path(current_user), notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to user_path(current_user), notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to user_brands_path, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.permit(:name, :logo, :user_id)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_edit_form.html.erb
<%= form_with url: user_brand_path, method: :patch do |form| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% form.hidden_field :user_id, value: params[:user_id] %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :brand_name %>
  </div>

  <div class="field">
    <%= form.label :logo %>
    <%= form.file_field :logo, id: :brand_logo %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/brands/_form.html.erb
<%= form_with url: user_brands_path do |form| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% form.hidden_field :user_id, value: params[:user_id] %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :brand_name, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :logo %>
    <%= form.file_field :logo, id: :brand_logo %>
  </div>
  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing Brand</h1>
<div>
	<p>Existing brand name: <%= @brand.name %></p>
	<p>Existing brand logo: <%= @brand.logo %></p>
</div>
<%= render 'edit_form', brand: @brand %>

<%= link_to 'Back', user_path(current_user) %>

app/views/brands/index.html.erb
<section class="dashboard-main">

<!-- Dashboard left panel -->
  <div class="dashboard-sub-left">
    <div class="dashboard-title">
      <a href="<%=user_path(current_user)%>"><h2><i class="fas fa-tachometer-alt"></i>&nbspDashboard</h2></a>
    </div>
    <div class="dashboard-sub-left-menu-container">
      <h3><i class="fas fa-edit"></i>&nbspManage</h3>
      <div class="dashboard-sub-left-menu">
        <div>
          <a href=<%= user_brands_path(current_user)%>>
            <h4><i class="fas fa-caret-right"></i>&nbspBrand</h4>
          </a>
          
        </div>
        <div>
          <a href="<%= user_archived_list_path(current_user)%>">
            <h4><i class="fas fa-caret-right"></i>&nbspArchives</h4>
          </a>
        </div>
      </div>
    </div>
    <div class="dashboard-sub-left-menu-container">
      <h3><i class="fas fa-user-circle"></i>&nbspAccount</h3>
      <div class="dashboard-sub-left-menu">
        <div>
          <a href=<%=edit_user_registration_path %>>
            <h4><i class="fas fa-caret-right"></i>&nbspManage Password</h4>
          </a>
        </div>
      </div>

    </div>
    <div class="dashboard-sub-left-menu-container dashboard-question">
      <a href="mailto:shanqyeet@gmail.com">
        <h3><i class="fas fa-question-circle"></i>&nbspSupport</h3>
      </a>
    </div>
  </div>


<!-- Dash bord right panel -->

  <!-- new form pop up -->
  <section class="form-lightbox">
    <article class="new-brand-form">
      <div class="new-brand-form-title">
        <div class="close-button-container">
          <a id="close-button" href="#"><strong>X</strong></a>
        </div>
        <h3>Create New Brand</h3>
      </div>
      <div class="new-brand-form-form">
        <%= render 'form', brand: @brand %>
      </div>
    </article>
  </section>

  <!-- display of list of items -->

  <div class="dashboard-sub-right">
      <h1>Manage Brands</h1>
      <button class="btn btn-lg btn-primary" id="create-brand-button">Create Brand</button>
    <section class="brands-list">
      <div class="row">
        <% if @brands.present? %> 
          <% @brands.each do |brand| %>
            <div class="brand-item col-lg-3">
              <% if brand.logo.file.nil? %>
                <%= image_tag("clipit-logo.png", width:"150px", height:"150px")%>
              <% else %>
                <img src=<%= brand.logo %> alt="" width="150px" height="150px">
              <% end %>
              <h5><%= brand.name %></h5>
              <div class="brand-items-edits">
              <%= button_to "delete", user_brand_path(id: brand.id), class:"btn btn-danger", data:{confirm:"WARNING: All CTAs and Clips associated with this logo will be deleted along with its statistics. Proceed?"}, method: :delete %> 
              </div>
            </div>
          <% end %>
        <% else %>
          <div class=".no-item-message" >
            <h4>You have not created any brand, create one today!</h4>
          </div>
        <% end %>
      </div>
    </section>

  </div>
</section>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Back', user_path(current_user) %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @brand.name %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @brand.logo %>
</p>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>